services:
    reverseproxy:
        build:
            dockerfile: Dockerfile.dev
            context: ./reverseproxy
        ports:
            - 8080:8080
        restart: always
        networks:
            - nebula-docker-compose_nebula-net

    frontend:
        build:
            dockerfile: Dockerfile.dev
            context: ./web
        command: ['/bin/bash', '-c', 'npm install && npm run dev']
        depends_on:
            - reverseproxy
        restart: always
        volumes:
            - ./web/frontend:/frontend
        networks:
            - nebula-docker-compose_nebula-net

    backend:
        depends_on:
            - reverseproxy
        command:
            [
                '/bin/bash',
                '-c',
                'uvicorn app.main:app --reload --host 0.0.0.0 --port 4000',
            ]
        build: backend
        restart: always
        volumes:
            - ./backend/src:/backend/app
        networks:
            - nebula-docker-compose_nebula-net
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]

networks:
    nebula-docker-compose_nebula-net:
        external: true
