services:
    reverseproxy:
        build: reverseproxy
        ports:
            - 8080:8080
        restart: always
        networks:
            - nebula-docker-compose_nebula-net

    frontend:
        build: web
        depends_on:
            - reverseproxy
        restart: always
        networks:
            - nebula-docker-compose_nebula-net

    backend:
        depends_on:
            - reverseproxy
        build: backend
        restart: always
        networks:
            - nebula-docker-compose_nebula-net
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]

networks:
    nebula-docker-compose_nebula-net:
        external: true
