services:
    reverseproxy:
        build: reverseproxy
        ports:
            - 8080:8080
        restart: always
        networks:
            - nebula-docker-compose_nebula-net

    frontend:
        build: web
        depends_on:
            - reverseproxy
        restart: always
        networks:
            - nebula-docker-compose_nebula-net

    backend:
        depends_on:
            - reverseproxy
        build: backend
        restart: always
        networks:
            - nebula-docker-compose_nebula-net
        environment:
            - CUDA_VISIBLE_DEVICES
            - VLLM_WORKER_MULTIPROC_METHOD=spawn
            - NCCL_IB_DISABLE=1
            # - NCCL_DEBUG=INFO
            # - NCCL_P2P_LEVEL=NODE
        shm_size: '48gb'
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]

networks:
    nebula-docker-compose_nebula-net:
        external: true
