data:
  document_paths:
    - 'processed_中美貿易戰禁令_202306-202401.json'
    - 'processed_矽光子發展_202306-202401.json'
    - 'processed_AI晶片發展_0-500_202306-202401.json'
    - 'processed_semiconductor_0-30000_articles_20230901-20230921.json'
nebula_graph:
  space_names:
    - 'asegptkg_rag_war'
    - 'asegptkg_rag_silicon'
    - 'asegptkg_rag_ai'
    - 'asegptkg_rag_semiconductor'
  persist_dirs:
    - '/app/storages/war'
    - '/app/storages/silicon'
    - '/app/storages/ai'
    - '/app/storages/semiconductor'
rag:
  generator_model_path: '/app/models/rag_ift_qlora_chat-vector/'
  query_engine_tools:
    - asegptkg_rag_war:
      - name: 'war_query_engine_tool'
      - description: 'Useful for answering questions about "China–United States trade war" and its impact on the world'
    - asegptkg_rag_silicon:
      - name: 'silicon_query_engine_tool'
      - description: 'Useful for answering questions about "Silicon Photonics development trend" and its impact on the world'
    - asegptkg_rag_ai:
      - name: 'ai_query_engine_tool'
      - description: 'Useful for answering questions about "Artificial Intelligence(AI)" and "AI Chips development trend" and its impact on the world'
    - asegptkg_rag_semiconductor:
      - name: 'semiconductor_query_engine_tool'
      - description: 'Useful for answering questions about "General Semiconductor development trend" or "Commonsense of Semiconductor".'
